Added new options to config section
umee-network/umee pull request #1108
Opened 2022-07-05 22:16 UTC by natexlee

## Description

closes: #XXXX

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-07-05 22:18 UTC, natexlee reviewed
Initial definitions/overview of the three new options.

2022-07-06 01:32 UTC, adamewozniak requested changes
Good start! Please update your PR title to adhere to the commit type syntax https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json

2022-07-06 01:32 UTC, adamewozniak commented on price-feeder/README.md
> +• A set of options for the /metrics endpoint when running the price feeder.
Let's try to be a bit more descriptive, use the same case they would in the config file (e.g., `deviation_thresholds` or `telemetry`, and add the same spacing we're using on other parts of the config list:
```suggestion
### `telemetry`

A set of options for the application's telemetry, which is disabled by default. An in-memory sink is the default, but Prometheus is also supported.
```

Maybe it'd be helpful to also link to the config here?

2022-07-06 01:32 UTC, adamewozniak commented on price-feeder/README.md
> +• Deviation allows validators to set a custom amount of standard deviations around the median which helps distinguish providers from other providers.
Add a note about how the default is for this is 1 standard deviation. 

Also, it's not for distinguishing providers from one another; this "deviation allowance" is supposed to help if any providers became faulty.

2022-07-07 00:16 UTC, natexlee reviewed
Documentation

2022-07-07 19:13 UTC, adamewozniak reviewed
Almost there, also need to update your PR title. Something like: 
docs: update price-feeder readme config section

2022-07-08 00:07 UTC, natexlee reviewed
Changes requested by Woz

2022-07-08 10:56 UTC, robert-zaremba reviewed
To be honest, I think it's better to have that documentation in the config file comments - it will be easier to maintain it.

2022-07-08 10:56 UTC, robert-zaremba commented on price-feeder/README.md
> +```
please add a link to cosmos-sdk telemetry: https://github.com/cosmos/cosmos-sdk/blob/main/docs/core/telemetry.md

2022-07-08 15:04 UTC, natexlee reviewed
added the link requested by Robert

2022-07-08 19:36 UTC, natexlee reviewed
fixed trailing spaces

2022-07-08 20:24 UTC, adamewozniak approved these changes
LGTM! Great job

2022-07-08 20:27 UTC, merged