add release tagging scheme for experimental releases
umee-network/umee pull request #1239
Opened 2022-08-12 21:04 UTC by dreamcodez

## Description

add release tagging scheme for experimental releases

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-08-12 21:37 UTC, UmeeAndrey approved these changes

2022-08-12 22:44 UTC, adamewozniak commented
imo we should discuss with the team whether or not we'd like to release alpha binaries before merging this  💯

2022-08-14 16:52 UTC, robert-zaremba commented
I second @adamewozniak . I don't see the reason why we should create a noise on github release page. `-alpa` / `-experimental` releases are not official. Moreover with go.mode links, this won't work.

2022-08-15 22:21 UTC, adamewozniak requested changes
gonna block this since we've agreed to only have RCs / official RCs in our meeting today

2022-08-17 12:43 UTC, robert-zaremba commented
Then let's close this PR. Good that we found a consensus.

2022-08-17 12:43 UTC, closed without merging