DNM: implement various token limits
umee-network/umee pull request #1319
Opened 2022-08-31 23:45 UTC by toteki

## Description

Note: don't merge this yet - it's currently targeted at the `adam/tests` branch to show the actual diff, but should be targeted at `main` once the tests are merged.

closes: #1227

---

### Author Checklist

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

2022-09-01 15:25 UTC, toteki commented
Note: this will stay draft while we decide if `MaxSupply` will remain a flat amount, or be changed to a share of USD value.

2022-09-06 15:50 UTC, robert-zaremba requested changes
Let's use share value with a minimum total collateral to trigger the limitation (can be hardcoded in v3 as 500k I would say - in other words, the MaxSupply check will be triggered only if TotalAllSuply is >= 500k USD)
+ https://umeeworkspace.slack.com/archives/C03CVS0459A/p1662143001347019?thread_ts=1662045844.731089&cid=C03CVS0459A
+ https://github.com/umee-network/umee/issues/1227#issuecomment-1233167479

2022-09-06 15:50 UTC, robert-zaremba commented on x/leverage/fixtures/token.go
> +		MaxSupply:              sdk.NewInt(100000_000000),
```suggestion
		MaxSupply:              sdk.NewInt(100_000_000000),
```

2022-09-06 15:50 UTC, robert-zaremba commented on x/leverage/keeper/keeper_test.go
> +	whale := s.newAccount(coin(umeeDenom, 1000000_000000))
```suggestion
	whale := s.newAccount(coin(umeeDenom, 1_000_000_000000))
```

2022-09-06 15:50 UTC, robert-zaremba commented on x/leverage/keeper/keeper_test.go
> +	whale := s.newAccount(coin(umeeDenom, 1000000_000000))
or... let's define and export in fixtures a `DefaultMaxSupply=100_000000` and here let's use `fixtures.DefaultMaxSupply*10`.

2022-09-06 15:50 UTC, robert-zaremba commented on x/leverage/keeper/keeper_test.go
> +			coin(umeeDenom, 1000000_000000),
ditto, let's use `DefaultMaxSupply*5` for example

2022-09-06 15:50 UTC, robert-zaremba commented on x/leverage/fixtures/token.go
> +		MaxSupply:              sdk.NewInt(100000_000000),
Also, we decided to use share value.

2022-09-06 19:04 UTC, toteki commented on x/leverage/fixtures/token.go
> +		MaxSupply:              sdk.NewInt(100000_000000),
We did not.

2022-09-06 21:35 UTC, robert-zaremba approved these changes
Following our discussion, we won't use that functionality. We can:
- leave this PR in draft
- or merge and add appropriate comments in the code
Do as you prefer.

2022-09-07 00:43 UTC, merged