feat: Add crypto.com provider
umee-network/umee pull request #1448
Opened 2022-09-26 18:29 UTC by rbajollari

## Description

closes: #1305 

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-10-03 14:27 UTC, RafilxTenfen commented on price-feeder/oracle/provider/crypto.go
> +		AskPrice       float64 `json:"k"` // The current best ask price, null if there aren't any asks
Maybe we could remove the fields we don't use ^^

2022-10-03 19:56 UTC, RafilxTenfen requested changes

2022-10-03 19:56 UTC, RafilxTenfen commented on price-feeder/oracle/provider/crypto.go
> +		p.pong(bz, reconnectTicker)
You could pass `heartbeatResp` to the pong func to not unmarshal it again

2022-10-03 19:56 UTC, RafilxTenfen commented on price-feeder/oracle/provider/crypto.go
> +	}
```suggestion
	price, err := coin.NewDecFromFloat(tickerPair.LatestTrade)
	if err != nil {
		p.logger.Warn().Err(err).Msg("crypto: failed to parse ticker price")
		return
	}
	volume, err := coin.NewDecFromFloat(tickerPair.Volume)
	if err != nil {
		p.logger.Warn().Err(err).Msg("crypto: failed to parse ticker volume")
		return
	}
```

We should not set if there is a problem with parsing values

2022-10-03 19:56 UTC, RafilxTenfen commented on price-feeder/oracle/provider/crypto.go
> +	}
```suggestion
	close, err := coin.NewDecFromFloat(candlePair.Close)
	if err != nil {
		p.logger.Warn().Err(err).Msg("crypto: failed to parse candle close")
		return
	}
	volume, err := coin.NewDecFromFloat(candlePair.Volume)
	if err != nil {
		p.logger.Warn().Err(err).Msg("crypto: failed to parse candle volume")
		return
	}
```

2022-10-03 19:56 UTC, RafilxTenfen commented on price-feeder/oracle/provider/crypto.go
> +func (p *CryptoProvider) GetAvailablePairs() (map[string]struct{}, error) {
this endpoint should return an map with the key as `CurrencyPair.String()` which it is "ATOMUSDT", at the moment it is returning "ATOM_USDT"

So, we need to parse it from `CryptoPairsSummary` to `CurrencyPair` and then `availablePairs[currencyPair.Sting()] = struct{}{}`

2022-10-03 23:56 UTC, rbajollari commented on price-feeder/oracle/provider/crypto.go
> +	subsMsgID, err := rand.Int(rand.Reader, big.NewInt(1000))
Did it at first thinking the sub id needs to be unique per request but its working now just using 1 as the ID everytime so I've changed it to be 1 all the time.

2022-10-04 23:38 UTC, rbajollari commented on price-feeder/oracle/provider/crypto.go
> +		TimeStamp: SecondsToMilli(candlePair.Timestamp),
https://exchange-docs.crypto.com/spot/index.html#candlestick-interval-instrument_name Yeah if you compare the "t" field in the response and the "nonce" in the request which is in unix milliseconds , the example response has "t" in unix seconds.

2022-10-05 17:57 UTC, RafilxTenfen approved these changes
So, the code looks great :100: 

but I was testing with "ATOM_USDT" and received some errors that I think they are okay 
![image](https://user-images.githubusercontent.com/17556614/194128799-fd89588d-91d4-4b3f-a35e-ab8e70e80710.png)

But just to note, after some time the crypto provider still was giving 
```shell
2:56PM WRN provider deviating from other candles base=ATOM module=oracle price=12.879940814866863791 provider=crypto
```
cc @adamewozniak

2022-10-05 18:42 UTC, merged