Enable snapshots
umee-network/umee pull request #1881
Opened 2023-03-02 08:32 UTC by freshe4qa

Enable snapshots to enable validators to more quickly deploy nodes/run experiments

## Description

closes: #XXXX

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2023-03-02 15:01 UTC, robert-zaremba reviewed
Thanks for contribution. Could you update the Changelog please?

2023-03-02 17:52 UTC, freshe4qa commented
>

2023-03-03 15:27 UTC, freshe4qa commented
@robert-zaremba done

2023-03-03 16:25 UTC, robert-zaremba commented
@freshe4qa did you push the changes? I don't see the changelog update.
Also, could you look at the failing tests?

2023-03-03 16:38 UTC, freshe4qa commented
@robert-zaremba i fix lint, check changes

2023-03-04 15:45 UTC, robert-zaremba commented
still the test and lint is failing.

2023-03-04 17:14 UTC, freshe4qa commented
Everyone has different Lint and other things set up. I won't fix anything there so as not to ruin what's already working. I think it is better for you to look at what can be fixed or someone from the team.

2023-03-16 18:43 UTC, robert-zaremba approved these changes
lint fix

2023-03-16 18:43 UTC, robert-zaremba commented on cmd/umeed/cmd/root.go
> +// Add snapshots
```suggestion
	// Add snapshots
```

2023-03-16 18:44 UTC, robert-zaremba commented
You should use `make lint` to make sure you use the same config as everyone in the repo. You won't need to install anything.

2023-03-16 19:34 UTC, robert-zaremba requested changes
in fact this seams to be a copy paste or a commit cherry pick and it's not compatible with the file,... that's why the build fails.

2023-03-16 19:37 UTC, robert-zaremba commented
snapshot is already implemented in https://github.com/umee-network/umee/blob/main/cmd/umeed/cmd/app_creator.go#L64

2023-03-16 19:37 UTC, closed without merging