chore: bump cosmwasm
umee-network/umee pull request #2011
Opened 2023-04-26 08:29 UTC by robert-zaremba

## Description

Replaces: #2004

* updating release notes
* this is in draft, and waiting for notional for a new release from their side (confirmed) - we don't need to do `replace` in go.mod

2023-05-17 10:31 UTC, gsk967 commented
@robert-zaremba could you check once the integration When i tried  to build the binary locally it is failing

2023-05-25 05:45 UTC, robert-zaremba commented
hmm, strange that this update breaks API

2023-05-25 06:28 UTC, gsk967 requested changes
Can you replace https://github.com/umee-network/umee/pull/2011/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L343


```github.com/tendermint/tendermint => github.com/cometbft/cometbft v0.34.28```

2023-05-26 06:45 UTC, gsk967 approved these changes

2023-05-26 07:08 UTC, merged