perf: remove unnecessary null byte
umee-network/umee pull request #2110
Opened 2023-06-23 15:03 UTC by robert-zaremba

## Description

followup to: #2101

2023-06-23 15:08 UTC, gsk967 approved these changes
LGTM

2023-06-23 15:20 UTC, toteki requested changes
discussion

2023-06-27 22:22 UTC, toteki commented on x/leverage/keeper/iter.go
> +	return store.SumCoins(k.prefixStore(ctx, types.KeyPrefixReserveAmount), keys.NoLastByte)
Doesn't this break mainnet? Leverage already stores these coins with null terminator

2023-06-27 22:25 UTC, toteki commented on x/incentive/keeper/iter.go
> +	return store.SumCoins(k.prefixStore(ctx, keyPrefixTotalBonded), keys.NoLastByte)
```suggestion
	return store.SumCoins(k.prefixStore(ctx, keyPrefixTotalBonded), keys.ToStr)
```

2023-06-28 00:26 UTC, toteki approved these changes

2023-06-28 13:52 UTC, toteki commented on x/leverage/keeper/iter.go
> +	return store.SumCoins(k.prefixStore(ctx, types.KeyPrefixReserveAmount), keys.NoLastByte)
ok

2023-06-28 14:16 UTC, merged