feat: additional x/leverage queries
umee-network/umee pull request #320
Opened 2021-12-21 16:55 UTC by toteki

## Description

Adds more queries (and CLI support) for x/leverage

Progress towards #93 and #94

----

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added appropriate labels to the PR
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2021-12-21 17:01 UTC, alexanderbez requested changes

2021-12-21 17:01 UTC, alexanderbez commented on x/leverage/client/cli/query.go
> +		GetCmdQueryCollateral(),
Can we add integration tests for these please?

2021-12-21 17:02 UTC, toteki commented on x/leverage/client/cli/query.go
> +func GetCmdQueryCollateralSetting() *cobra.Command {
```suggestion
// GetCmdQueryCollateral returns a CLI command handler to query for the amount of
// total collateral tokens for a given address.
func GetCmdQueryCollateral() *cobra.Command {
```

2021-12-21 17:04 UTC, toteki commented on x/leverage/client/cli/query.go
> +func GetCmdQueryCollateral() *cobra.Command {
```suggestion
// GetCmdQueryCollateralSetting returns a CLI command handler to query for the collateral
// setting of a specific token denom for an address.
func GetCmdQueryCollateralSetting() *cobra.Command {
```

2021-12-22 22:40 UTC, toteki commented
R4R again - note that the tests in `client/tests/suite.go` are still at a bare minimum - the next PR will flesh them out (table-driven, additional setup, etc).

2021-12-22 23:24 UTC, adamewozniak commented on x/leverage/keeper/grpc_query.go
> +
```suggestion
```

2021-12-22 23:24 UTC, adamewozniak commented on x/leverage/keeper/grpc_query.go
> +
```suggestion
```

2021-12-22 23:24 UTC, adamewozniak commented on x/leverage/keeper/grpc_query.go
> +
same for the rest of them
```suggestion
```

2021-12-23 15:02 UTC, alexanderbez approved these changes

2021-12-23 15:02 UTC, alexanderbez commented on x/leverage/client/tests/cli_test.go
> +func (s *IntegrationTestSuite) TearDownSuite() {
Good catch. Thanks!

2021-12-23 15:02 UTC, alexanderbez commented on x/leverage/keeper/collateral.go
> +func (k Keeper) GetEligibleLiquidationTargets(ctx sdk.Context) ([]sdk.AccAddress, error) {
Do we actually need this to be defined in the state-machine? Can the tool not just query on-chain state to figure out the targets?

Granted, we could just build the query for them too...

2021-12-23 16:21 UTC, merged