fix: track uToken supply manually
umee-network/umee pull request #504
Opened 2022-02-07 17:01 UTC by toteki

## Description

Fixes issue found in TrailOfBits audit

Closes #505 

----

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] added appropriate labels to the PR
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [x] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [x] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-02-07 19:24 UTC, alexanderbez requested changes

2022-02-07 19:24 UTC, alexanderbez commented on proto/umee/leverage/v1beta1/genesis.proto
> +  repeated cosmos.base.v1beta1.Coin utoken_supplies = 10
```suggestion
  repeated cosmos.base.v1beta1.Coin utoken_supply = 10
```

2022-02-07 19:24 UTC, alexanderbez commented on x/leverage/keeper/genesis.go
> +		k.GetAllUTokenSupplies(ctx),
```suggestion
		k.GetAllUTokenSupply(ctx),
```

2022-02-08 14:29 UTC, alexanderbez approved these changes
👏

2022-02-08 14:59 UTC, toteki commented
Looking into failing e2e

2022-02-08 21:27 UTC, merged